HERO_ROLES = {
'npc_dota_hero_antimage': ['melee', 'carry', 'escape', 'initiator', 'nuker'],
'npc_dota_hero_axe': ['melee', 'durable', 'initiator', 'offlaner', 'jungler'],
'npc_dota_hero_bane': ['ranged', 'support', 'lockdown', 'disarm'],
'npc_dota_hero_bloodseeker': ['melee', 'carry', 'silence', 'lockdown', 'amplify'],
'npc_dota_hero_crystal_maiden': ['ranged', 'support', 'jungler', 'lockdown', 'slow', 'nuker'],
'npc_dota_hero_drow_ranger': ['ranged', 'carry', 'slow', 'silence', 'amplify'],
'npc_dota_hero_earthshaker': ['melee', 'support', 'lockdown', 'nuker'],
'npc_dota_hero_juggernaut': ['melee', 'carry', 'nuker', 'healer'],
'npc_dota_hero_mirana': ['ranged', 'lockdown', 'nuker', 'offlaner', 'carry', 'escape', 'initiator'],
'npc_dota_hero_nevermore': ['ranged', 'carry', 'nuker'],
'npc_dota_hero_morphling': ['ranged', 'carry', 'nuker', 'lockdown', 'escape', 'initiator', 'durable'],
'npc_dota_hero_phantom_lancer': ['melee', 'nuker', 'carry', 'escape'],
'npc_dota_hero_puck': ['ranged', 'initiator', 'escape', 'nuker', 'lockdown', 'silence'],
'npc_dota_hero_pudge': ['melee', 'lockdown', 'initiator', 'durable', 'slow'],
'npc_dota_hero_razor': ['ranged', 'durable', 'nuker', 'carry'],
'npc_dota_hero_sand_king': ['melee', 'nuker', 'lockdown', 'escape', 'initiator', 'support', 'jungler'],
'npc_dota_hero_storm_spirit': ['ranged', 'initiator', 'escape', 'carry', 'lockdown', 'nuker'],
'npc_dota_hero_sven': ['melee', 'lockdown', 'carry', 'amplify'],
'npc_dota_hero_tiny': ['melee', 'lockdown', 'carry', 'nuker'],
'npc_dota_hero_vengefulspirit': ['ranged', 'lockdown', 'support', 'initiator'],
'npc_dota_hero_windrunner': ['ranged', 'lockdown', 'nuker', 'support', 'offlaner', 'carry'],
'npc_dota_hero_zuus': ['ranged', 'nuker', 'carry'],
'npc_dota_hero_kunkka': ['melee', 'carry', 'nuker', 'lockdown'],
'npc_dota_hero_lina': ['ranged', 'nuker', 'carry', 'support', 'lockdown'],
'npc_dota_hero_lich': ['ranged', 'nuker', 'slow', 'support', 'amplify'],
'npc_dota_hero_lion': ['ranged', 'nuker', 'lockdown', 'support'],
'npc_dota_hero_shadow_shaman': ['ranged', 'nuker', 'support', 'pusher'],
'npc_dota_hero_slardar': ['melee', 'lockdown', 'amplify', 'carry', 'offlaner'],
'npc_dota_hero_tidehunter': ['melee', 'lockdown', 'durable', 'slow', 'nuker'],
'npc_dota_hero_witch_doctor': ['ranged', 'lockdown', 'nuker', 'support', 'healer'],
'npc_dota_hero_riki': ['melee', 'escape', 'silence', 'carry'],
'npc_dota_hero_enigma': ['ranged', 'jungler', 'lockdown'],
'npc_dota_hero_tinker': ['ranged', 'carry', 'pusher', 'nuker', 'disarm'],
'npc_dota_hero_sniper': ['ranged', 'carry', 'nuker'],
'npc_dota_hero_necrolyte': ['ranged', 'nuker', 'healer', 'carry', 'support', 'lockdown'],
'npc_dota_hero_warlock': ['ranged', 'support', 'lockdown', 'healer', 'slow'],
'npc_dota_hero_beastmaster': ['melee', 'jungler', 'offlane', 'durable', 'initiator', 'lockdown', 'nuker'],
'npc_dota_hero_queenofpain': ['ranged', 'slow', 'nuker', 'escape', 'initiator'],
'npc_dota_hero_venomancer': ['ranged', 'slow', 'pusher', 'nuker', 'support'],
'npc_dota_hero_faceless_void': ['melee', 'lockdown', 'carry', 'offlaner', 'slow', 'escape', 'initiator'],
'npc_dota_hero_skeleton_king': ['melee', 'durable', 'lockdown', 'carry', 'jungler'],
'npc_dota_hero_death_prophet': ['ranged', 'pusher', 'carry', 'nuker', 'silence'],
'npc_dota_hero_phantom_assassin': ['melee', 'carry', 'initiator', 'slow'],
'npc_dota_hero_pugna': ['ranged', 'nuker', 'support'],
'npc_dota_hero_templar_assassin': ['ranged', 'carry', 'initiator', 'escape', 'slow'],
'npc_dota_hero_viper': ['ranged', 'slow', 'durable', 'carry'],
'npc_dota_hero_luna': ['ranged', 'support', 'carry', 'lockdown', 'nuker'],
'npc_dota_hero_dragon_knight': ['ranged', 'melee', 'durable', 'lockdown', 'nuker', 'carry'],
'npc_dota_hero_dazzle': ['ranged', 'support', 'amplify', 'slow', 'nuker', 'healer'],
'npc_dota_hero_rattletrap': ['melee', 'lockdown', 'offlaner', 'nuker'],
'npc_dota_hero_leshrac': ['ranged', 'nuker', 'support', 'carry', 'lockdown', 'slow'],
'npc_dota_hero_furion': ['ranged', 'offlaner', 'jungler', 'nuker'],
'npc_dota_hero_life_stealer': ['melee', 'slow', 'carry', 'initiator', 'escape', 'amplify'],
'npc_dota_hero_dark_seer': ['melee', 'offlaner', 'jungler', 'escape', 'initiator'],
'npc_dota_hero_clinkz': ['ranged', 'carry', 'escape', 'initiator'],
'npc_dota_hero_omniknight': ['melee', 'slow', 'nuker', 'support', 'healer'],
'npc_dota_hero_enchantress': ['ranged', 'support', 'jungler', 'healer', 'nuker', 'slow', 'lockdown'],
'npc_dota_hero_huskar': ['melee', 'carry', 'initiator', 'healer'],
'npc_dota_hero_night_stalker': ['melee', 'initiator', 'nuker', 'silence', 'slow'],
'npc_dota_hero_broodmother': ['melee', 'escape', 'nuker', 'pusher', 'offlaner'],
'npc_dota_hero_bounty_hunter': ['melee', 'nuker', 'offlaner', 'slow'],
'npc_dota_hero_weaver': ['ranged', 'carry', 'offlaner'],
'npc_dota_hero_jakiro': ['ranged', 'support', 'lockdown', 'slow'],
'npc_dota_hero_batrider': ['ranged', 'lockdown', 'jungler', 'offlaner'],
'npc_dota_hero_chen': ['ranged', 'jungler', 'nuker', 'lockdown', 'support', 'healer'],
'npc_dota_hero_spectre': ['melee', 'carry', 'initiator', 'escape'],
'npc_dota_hero_doom_bringer': ['melee', 'durable', 'carry', 'offlaner', 'jungler', 'silence'],
'npc_dota_hero_ancient_apparition': ['ranged', 'slow', 'support', 'nuker'],
'npc_dota_hero_ursa': ['melee', 'carry', 'slow'],
'npc_dota_hero_spirit_breaker': ['melee', 'initiator', 'escape', 'offlaner', 'lockdown'],
'npc_dota_hero_gyrocopter': ['ranged', 'carry', 'lockdown', 'nuker'],
'npc_dota_hero_alchemist': ['melee', 'carry', 'lockdown', 'amplify'],
'npc_dota_hero_invoker': ['ranged', 'nuker', 'carry', 'lockdown', 'initiator', 'escape'],
'npc_dota_hero_silencer': ['ranged', 'support', 'silence'],
'npc_dota_hero_obsidian_destroyer': ['ranged', 'disabler', 'lockdown', 'nuker'],
'npc_dota_hero_lycan': ['melee', 'carry', 'escape', 'jungler'],
'npc_dota_hero_brewmaster': ['melee', 'initiator', 'disabler', 'lockdown', 'nuker'],
'npc_dota_hero_shadow_demon': ['ranged', 'support', 'disabler', 'lockdown', 'slow'],
'npc_dota_hero_lone_druid': ['melee', 'carry', 'disabler', 'lockdown', 'durable'],
'npc_dota_hero_chaos_knight': ['melee', 'disabler', 'lockdown', 'initiator', 'carry'],
'npc_dota_hero_meepo': ['melee', 'disabler', 'lockdown', 'nuker', 'carry'],
'npc_dota_hero_treant': ['melee', 'disabler', 'durable', 'escape', 'initiator', 'support', 'slow'],
'npc_dota_hero_ogre_magi': ['melee', 'disabler', 'healer', 'durable', 'initiator', 'nuker', 'support', 'slow', 'lockdown', 'amplify'],
'npc_dota_hero_undying': ['melee', 'disabler', 'healer', 'durable', 'nuker', 'support', 'amplify'],
'npc_dota_hero_rubick': ['ranged', 'disabler', 'nuker', 'support', 'lockdown'],
'npc_dota_hero_disruptor': ['ranged', 'disabler', 'initiator', 'nuker', 'support', 'lockdown', 'silence'],
'npc_dota_hero_nyx_assassin': ['melee', 'disabler', 'escape', 'initiator', 'nuker', 'lockdown'],
'npc_dota_hero_naga_siren': ['melee', 'carry', 'disabler', 'escape', 'initiator', 'pusher', 'support', 'lockdown'],
'npc_dota_hero_keeper_of_the_light': ['ranged', 'disabler', 'jungler', 'nuker', 'support'],
'npc_dota_hero_wisp': ['ranged', 'healer', 'escape', 'nuker', 'support', 'amplify'],
'npc_dota_hero_visage': ['ranged', 'disabler', 'durable', 'nuker', 'pusher', 'support', 'slow'],
'npc_dota_hero_slark': ['melee', 'carry', 'disabler', 'escape', 'nuker', 'lockdown'],
'npc_dota_hero_medusa': ['ranged', 'carry', 'disabler', 'durable', 'lockdown'],
'npc_dota_hero_troll_warlord': ['ranged', 'carry', 'disabler', 'durable', 'pusher', 'amplify'],
'npc_dota_hero_centaur': ['melee', 'disabler', 'durable', 'escape', 'initiator', 'nuker', 'lockdown'],
'npc_dota_hero_magnataur': ['melee', 'disabler', 'escape', 'initiator', 'nuker', 'lockdown'],
'npc_dota_hero_shredder': ['melee', 'durable', 'escape', 'nuker', 'slow'],
'npc_dota_hero_bristleback': ['melee', 'carry', 'durable', 'initiator', 'nuker', 'slow'],
'npc_dota_hero_tusk': ['melee', 'disabler', 'initiator', 'nuker'],
'npc_dota_hero_skywrath_mage': ['ranged', 'disabler', 'nuker', 'support', 'slow', 'silence', 'amplify'],
'npc_dota_hero_abaddon': ['melee','carry', 'durable', 'support'],
'npc_dota_hero_elder_titan': ['melee', 'disabler', 'initiator', 'nuker', 'lockdown'],
'npc_dota_hero_legion_commander': ['melee', 'carry', 'disabler', 'durable', 'initiator', 'nuker', 'lockdown'],
'npc_dota_hero_ember_spirit': ['melee', 'carry', 'disabler', 'escape', 'initiator', 'nuker', 'lockdown'],
'npc_dota_hero_earth_spirit': ['melee', 'disabler', 'escape', 'initiator', 'nuker', 'silence'],
'npc_dota_hero_terrorblade': ['melee', 'carry', 'nuker', 'pusher', 'slow'],
'npc_dota_hero_phoenix': ['ranged', 'healer', 'disbler', 'escape', 'initiator', 'nuker', 'support', 'slow'],
'npc_dota_hero_oracle': ['ranged', 'header', 'disabler', 'escape', 'nuker', 'support', 'disarm', 'lockdown'],
'npc_dota_hero_techies': ['ranged', 'disabler', 'nuker', 'lockdown'],
'npc_dota_hero_winter_wyvern': ['ranged', 'healer', 'disabler', 'nuker', 'support', 'slow'],
'npc_dota_hero_arc_warden': ['ranged', 'carry', 'nuker', 'escape', 'disarm'],
}